### ISSUE TITLE
Whisper Metaflow pipeline

### ISSUE THREAD

**Issue by mrharpo** [WGBH-MLA/mario#1]
Create Metaflow FlowSpec for Whisper-bot
```[tasklist]
### Tasks
- [x] Resolve guid to SonyCi asset ID
- [x] Download file from SonyCi
- [x] Run whisper
- [x] Enable GPU
- [x] Upload transcript to s3
- [x] Clean files
```
