### ISSUE TITLE
app-whisper v3

### ISSUE THREAD

**Issue by mrharpo** [WGBH-MLA/mario#8]
```[tasklist]
### Tasks
- [x] Deploy app-whisper:v3
- [x] Add gpu taint
- [x] Add gpu tolerance
- [x] Convert Whisper flow to call app-whisper
- [x] Add to chowda db
- [x] Deploy to argo
```
